/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 8 "./lbm_1d_array.h"
typedef double LBM_Grid[26000000];
#line 9 "./lbm_1d_array.h"
typedef LBM_Grid *LBM_GridPtr;
#line 140 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 141 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 46 "/home/codeman/.itsoflife/mydata/local/packages-live/llvm-clang9.0.0/build/lib/clang/9.0.0/include/stddef.h"
typedef unsigned long size_t;
#line 4 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h"
struct _IO_FILE;
#line 7 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h"
typedef struct _IO_FILE FILE;
#line 154 "/usr/include/x86_64-linux-gnu/bits/libio.h"
typedef void _IO_lock_t;
#line 160 "/usr/include/x86_64-linux-gnu/bits/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 245 "/usr/include/x86_64-linux-gnu/bits/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 27 "./main.h"
enum __anonenum_MAIN_Action_1 {
    NOTHING = 0,
    COMPARE = 1,
    STORE = 2
} ;
#line 27 "./main.h"
typedef enum __anonenum_MAIN_Action_1 MAIN_Action;
#line 28
enum __anonenum_MAIN_SimType_2 {
    LDC = 0,
    CHANNEL = 1
} ;
#line 28 "./main.h"
typedef enum __anonenum_MAIN_SimType_2 MAIN_SimType;
#line 30 "./main.h"
struct __anonstruct_MAIN_Param_3 {
   int nTimeSteps ;
   char *resultFilename ;
   MAIN_Action action ;
   MAIN_SimType simType ;
   char *obstacleFilename ;
};
#line 30 "./main.h"
typedef struct __anonstruct_MAIN_Param_3 MAIN_Param;
#line 133 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __dev_t;
#line 134 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __uid_t;
#line 135 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __gid_t;
#line 136 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __ino_t;
#line 138 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __mode_t;
#line 139 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __nlink_t;
#line 148 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
#line 162 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blksize_t;
#line 167 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blkcnt_t;
#line 184 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __syscall_slong_t;
#line 8 "/usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h"
struct timespec {
   __time_t tv_sec ;
   __syscall_slong_t tv_nsec ;
};
#line 46 "/usr/include/x86_64-linux-gnu/bits/stat.h"
struct stat {
   __dev_t st_dev ;
   __ino_t st_ino ;
   __nlink_t st_nlink ;
   __mode_t st_mode ;
   __uid_t st_uid ;
   __gid_t st_gid ;
   int __pad0 ;
   __dev_t st_rdev ;
   __off_t st_size ;
   __blksize_t st_blksize ;
   __blkcnt_t st_blocks ;
   struct timespec st_atim ;
   struct timespec st_mtim ;
   struct timespec st_ctim ;
   __syscall_slong_t __glibc_reserved[3] ;
};
#line 1 "lbm.o"
#pragma merger("0","/tmp/cil-iB9lzqzF.i","")
#line 30 "./lbm.h"
void LBM_allocateGrid(double **ptr ) ;
#line 31
void LBM_freeGrid(double **ptr ) ;
#line 32
void LBM_initializeGrid(double *grid ) ;
#line 33
void LBM_initializeSpecialCellsForLDC(double *grid ) ;
#line 34
void LBM_loadObstacleFile(double *grid , char const   *filename ) ;
#line 35
void LBM_initializeSpecialCellsForChannel(double *grid ) ;
#line 36
void LBM_swapGrids(LBM_GridPtr *grid1 , LBM_GridPtr *grid2 ) ;
#line 37
void LBM_performStreamCollide(double *srcGrid___0 , double *dstGrid___0 ) ;
#line 38
void LBM_handleInOutFlow(double *srcGrid___0 ) ;
#line 39
void LBM_showGridStatistics(double *grid ) ;
#line 40
void LBM_storeVelocityField(double *grid , char const   *filename , int const   binary ) ;
#line 42
void LBM_compareVelocityField(double *grid , char const   *filename , int const   binary ) ;
#line 143 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h"
extern  __attribute__((__nothrow__)) double sqrt(double __x ) ;
#line 539 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__)) ;
#line 563
extern  __attribute__((__nothrow__)) void free(void *__ptr ) ;
#line 614
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status ) ;
#line 199 "/usr/include/stdio.h"
extern int fclose(FILE *__stream ) ;
#line 232
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
#line 312
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 318
extern int printf(char const   * __restrict  __format  , ...) ;
#line 377
extern int fscanf(FILE * __restrict  __stream , char const   * __restrict  __format 
                  , ...)  __asm__("__isoc99_fscanf")  ;
#line 477
extern int fgetc(FILE *__stream ) ;
#line 646
extern size_t fread(void * __restrict  __ptr , size_t __size , size_t __n , FILE * __restrict  __stream ) ;
#line 652
extern size_t fwrite(void const   * __restrict  __ptr , size_t __size , size_t __n ,
                     FILE * __restrict  __s ) ;
#line 25 "lbm.c"
void LBM_allocateGrid(double **ptr ) 
{ 
  size_t margin ;
  size_t size ;
  void *tmp ;

  {
#line 26
  margin = (size_t )400000;
#line 26
  size = sizeof(LBM_Grid ) + (2UL * margin) * sizeof(double );
#line 29
  tmp = malloc(size);
#line 29
  *ptr = (double *)tmp;
#line 30
  if (! *ptr) {
#line 31
    printf((char const   * __restrict  )"LBM_allocateGrid: could not allocate %.1f MByte\n",
           (double )size / (1024.0 * 1024.0));
#line 33
    exit(1);
  }
#line 39
  *ptr += margin;
#line 40
  return;
}
}
#line 44 "lbm.c"
void LBM_freeGrid(double **ptr ) 
{ 
  size_t margin ;

  {
#line 45
  margin = (size_t )400000;
#line 47
  free((void *)(*ptr - margin));
#line 48
  *ptr = (double *)((void *)0);
#line 49
  return;
}
}
#line 53 "lbm.c"
void LBM_initializeGrid(double *grid ) 
{ 
  int i ;
  unsigned int *_aux_ ;

  {
#line 62
  i = -400000;
#line 62
  while (i < 26400000) {
#line 63
    *(grid + i) = 1.0 / 3.0;
#line 64
    *(grid + (1 + i)) = 1.0 / 18.0;
#line 65
    *(grid + (2 + i)) = 1.0 / 18.0;
#line 66
    *(grid + (3 + i)) = 1.0 / 18.0;
#line 67
    *(grid + (4 + i)) = 1.0 / 18.0;
#line 68
    *(grid + (5 + i)) = 1.0 / 18.0;
#line 69
    *(grid + (6 + i)) = 1.0 / 18.0;
#line 70
    *(grid + (7 + i)) = 1.0 / 36.0;
#line 71
    *(grid + (8 + i)) = 1.0 / 36.0;
#line 72
    *(grid + (9 + i)) = 1.0 / 36.0;
#line 73
    *(grid + (10 + i)) = 1.0 / 36.0;
#line 74
    *(grid + (11 + i)) = 1.0 / 36.0;
#line 75
    *(grid + (12 + i)) = 1.0 / 36.0;
#line 76
    *(grid + (13 + i)) = 1.0 / 36.0;
#line 77
    *(grid + (14 + i)) = 1.0 / 36.0;
#line 78
    *(grid + (15 + i)) = 1.0 / 36.0;
#line 79
    *(grid + (16 + i)) = 1.0 / 36.0;
#line 80
    *(grid + (17 + i)) = 1.0 / 36.0;
#line 81
    *(grid + (18 + i)) = 1.0 / 36.0;
#line 83
    _aux_ = (unsigned int *)((void *)(grid + (19 + i)));
#line 83
    *_aux_ = 0U;
#line 62
    i += 20;
  }
#line 85
  return;
}
}
#line 89 "lbm.c"
void LBM_swapGrids(LBM_GridPtr *grid1 , LBM_GridPtr *grid2 ) 
{ 
  LBM_GridPtr aux ;

  {
#line 90
  aux = *grid1;
#line 91
  *grid1 = *grid2;
#line 92
  *grid2 = aux;
#line 93
  return;
}
}
#line 97 "lbm.c"
void LBM_loadObstacleFile(double *grid , char const   *filename ) 
{ 
  int x ;
  int y ;
  int z ;
  FILE *file ;
  FILE *tmp ;
  unsigned int *_aux_ ;
  int tmp___0 ;

  {
#line 100
  tmp = fopen((char const   * __restrict  )filename, (char const   * __restrict  )"rb");
#line 100
  file = tmp;
#line 102
  z = 0;
#line 102
  while (z < 130) {
#line 103
    y = 0;
#line 103
    while (y < 100) {
#line 104
      x = 0;
#line 104
      while (x < 100) {
#line 105
        tmp___0 = fgetc(file);
#line 105
        if (tmp___0 != 46) {
#line 105
          _aux_ = (unsigned int *)((void *)(grid + (19 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 105
          *_aux_ |= 1U;
        }
#line 104
        x ++;
      }
#line 107
      fgetc(file);
#line 103
      y ++;
    }
#line 109
    fgetc(file);
#line 102
    z ++;
  }
#line 112
  fclose(file);
#line 113
  return;
}
}
#line 117 "lbm.c"
void LBM_initializeSpecialCellsForLDC(double *grid ) 
{ 
  int x ;
  int y ;
  int z ;
  unsigned int *_aux_ ;
  unsigned int *_aux____0 ;

  {
#line 126
  z = -2;
#line 126
  while (z < 132) {
#line 127
    y = 0;
#line 127
    while (y < 100) {
#line 128
      x = 0;
#line 128
      while (x < 100) {
#line 129
        if (x == 0) {
#line 132
          _aux_ = (unsigned int *)((void *)(grid + (19 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 132
          *_aux_ |= 1U;
        } else
#line 129
        if (x == 99) {
#line 132
          _aux_ = (unsigned int *)((void *)(grid + (19 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 132
          *_aux_ |= 1U;
        } else
#line 129
        if (y == 0) {
#line 132
          _aux_ = (unsigned int *)((void *)(grid + (19 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 132
          *_aux_ |= 1U;
        } else
#line 129
        if (y == 99) {
#line 132
          _aux_ = (unsigned int *)((void *)(grid + (19 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 132
          *_aux_ |= 1U;
        } else
#line 129
        if (z == 0) {
#line 132
          _aux_ = (unsigned int *)((void *)(grid + (19 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 132
          *_aux_ |= 1U;
        } else
#line 129
        if (z == 129) {
#line 132
          _aux_ = (unsigned int *)((void *)(grid + (19 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 132
          *_aux_ |= 1U;
        } else
#line 135
        if (z == 1) {
#line 135
          goto _L;
        } else
#line 135
        if (z == 128) {
          _L: /* CIL Label */ 
#line 135
          if (x > 1) {
#line 135
            if (x < 98) {
#line 135
              if (y > 1) {
#line 135
                if (y < 98) {
#line 138
                  _aux____0 = (unsigned int *)((void *)(grid + (19 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 138
                  *_aux____0 |= 2U;
                }
              }
            }
          }
        }
#line 128
        x ++;
      }
#line 127
      y ++;
    }
#line 126
    z ++;
  }
#line 144
  return;
}
}
#line 148 "lbm.c"
void LBM_initializeSpecialCellsForChannel(double *grid ) 
{ 
  int x ;
  int y ;
  int z ;
  unsigned int *_aux_ ;
  unsigned int *_aux____0 ;

  {
#line 157
  z = -2;
#line 157
  while (z < 132) {
#line 158
    y = 0;
#line 158
    while (y < 100) {
#line 159
      x = 0;
#line 159
      while (x < 100) {
#line 160
        if (x == 0) {
#line 160
          goto _L___0;
        } else
#line 160
        if (x == 99) {
#line 160
          goto _L___0;
        } else
#line 160
        if (y == 0) {
#line 160
          goto _L___0;
        } else
#line 160
        if (y == 99) {
          _L___0: /* CIL Label */ 
#line 162
          _aux_ = (unsigned int *)((void *)(grid + (19 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 162
          *_aux_ |= 1U;
#line 164
          if (z == 0) {
#line 164
            goto _L;
          } else
#line 164
          if (z == 129) {
            _L: /* CIL Label */ 
#line 164
            if (! (*((unsigned int *)((void *)(grid + (19 + 20 * ((x + y * 100) + (z * 100) * 100))))) & 1U)) {
#line 166
              _aux____0 = (unsigned int *)((void *)(grid + (19 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 166
              *_aux____0 |= 4U;
            }
          }
        }
#line 159
        x ++;
      }
#line 158
      y ++;
    }
#line 157
    z ++;
  }
#line 171
  return;
}
}
#line 175 "lbm.c"
void LBM_performStreamCollide(double *srcGrid___0 , double *dstGrid___0 ) 
{ 
  int i ;
  double ux ;
  double uy ;
  double uz ;
  double u2 ;
  double rho ;

  {
#line 186
  i = 0;
#line 186
  while (i < 26000000) {
#line 187
    if (*((unsigned int *)((void *)(srcGrid___0 + (19 + i)))) & 1U) {
#line 188
      *(dstGrid___0 + i) = *(srcGrid___0 + i);
#line 189
      *(dstGrid___0 + (-1998 + i)) = *(srcGrid___0 + (1 + i));
#line 190
      *(dstGrid___0 + (2001 + i)) = *(srcGrid___0 + (2 + i));
#line 191
      *(dstGrid___0 + (-16 + i)) = *(srcGrid___0 + (3 + i));
#line 192
      *(dstGrid___0 + (23 + i)) = *(srcGrid___0 + (4 + i));
#line 193
      *(dstGrid___0 + (-199994 + i)) = *(srcGrid___0 + (5 + i));
#line 194
      *(dstGrid___0 + (200005 + i)) = *(srcGrid___0 + (6 + i));
#line 195
      *(dstGrid___0 + (-2010 + i)) = *(srcGrid___0 + (7 + i));
#line 196
      *(dstGrid___0 + (-1971 + i)) = *(srcGrid___0 + (8 + i));
#line 197
      *(dstGrid___0 + (1988 + i)) = *(srcGrid___0 + (9 + i));
#line 198
      *(dstGrid___0 + (2027 + i)) = *(srcGrid___0 + (10 + i));
#line 199
      *(dstGrid___0 + (-201986 + i)) = *(srcGrid___0 + (11 + i));
#line 200
      *(dstGrid___0 + (198013 + i)) = *(srcGrid___0 + (12 + i));
#line 201
      *(dstGrid___0 + (-197988 + i)) = *(srcGrid___0 + (13 + i));
#line 202
      *(dstGrid___0 + (202011 + i)) = *(srcGrid___0 + (14 + i));
#line 203
      *(dstGrid___0 + (-200002 + i)) = *(srcGrid___0 + (15 + i));
#line 204
      *(dstGrid___0 + (199997 + i)) = *(srcGrid___0 + (16 + i));
#line 205
      *(dstGrid___0 + (-199964 + i)) = *(srcGrid___0 + (17 + i));
#line 206
      *(dstGrid___0 + (200035 + i)) = *(srcGrid___0 + (18 + i));
#line 207
      goto __Cont;
    }
#line 210
    rho = (((((((((((((((((*(srcGrid___0 + i) + *(srcGrid___0 + (1 + i))) + *(srcGrid___0 + (2 + i))) + *(srcGrid___0 + (3 + i))) + *(srcGrid___0 + (4 + i))) + *(srcGrid___0 + (5 + i))) + *(srcGrid___0 + (6 + i))) + *(srcGrid___0 + (7 + i))) + *(srcGrid___0 + (8 + i))) + *(srcGrid___0 + (9 + i))) + *(srcGrid___0 + (10 + i))) + *(srcGrid___0 + (11 + i))) + *(srcGrid___0 + (12 + i))) + *(srcGrid___0 + (13 + i))) + *(srcGrid___0 + (14 + i))) + *(srcGrid___0 + (15 + i))) + *(srcGrid___0 + (16 + i))) + *(srcGrid___0 + (17 + i))) + *(srcGrid___0 + (18 + i));
#line 221
    ux = ((((((((*(srcGrid___0 + (3 + i)) - *(srcGrid___0 + (4 + i))) + *(srcGrid___0 + (7 + i))) - *(srcGrid___0 + (8 + i))) + *(srcGrid___0 + (9 + i))) - *(srcGrid___0 + (10 + i))) + *(srcGrid___0 + (15 + i))) + *(srcGrid___0 + (16 + i))) - *(srcGrid___0 + (17 + i))) - *(srcGrid___0 + (18 + i));
#line 226
    uy = ((((((((*(srcGrid___0 + (1 + i)) - *(srcGrid___0 + (2 + i))) + *(srcGrid___0 + (7 + i))) + *(srcGrid___0 + (8 + i))) - *(srcGrid___0 + (9 + i))) - *(srcGrid___0 + (10 + i))) + *(srcGrid___0 + (11 + i))) + *(srcGrid___0 + (12 + i))) - *(srcGrid___0 + (13 + i))) - *(srcGrid___0 + (14 + i));
#line 231
    uz = ((((((((*(srcGrid___0 + (5 + i)) - *(srcGrid___0 + (6 + i))) + *(srcGrid___0 + (11 + i))) - *(srcGrid___0 + (12 + i))) + *(srcGrid___0 + (13 + i))) - *(srcGrid___0 + (14 + i))) + *(srcGrid___0 + (15 + i))) - *(srcGrid___0 + (16 + i))) + *(srcGrid___0 + (17 + i))) - *(srcGrid___0 + (18 + i));
#line 237
    ux /= rho;
#line 238
    uy /= rho;
#line 239
    uz /= rho;
#line 241
    if (*((unsigned int *)((void *)(srcGrid___0 + (19 + i)))) & 2U) {
#line 242
      ux = 0.005;
#line 243
      uy = 0.002;
#line 244
      uz = 0.000;
    }
#line 247
    u2 = 1.5 * ((ux * ux + uy * uy) + uz * uz);
#line 248
    *(dstGrid___0 + i) = (1.0 - 1.95) * *(srcGrid___0 + i) + (((1.0 / 3.0) * 1.95) * rho) * (1.0 - u2);
#line 250
    *(dstGrid___0 + (2001 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (1 + i)) + (((1.0 / 18.0) * 1.95) * rho) * ((1.0 + uy * (4.5 * uy + 3.0)) - u2);
#line 251
    *(dstGrid___0 + (-1998 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (2 + i)) + (((1.0 / 18.0) * 1.95) * rho) * ((1.0 + uy * (4.5 * uy - 3.0)) - u2);
#line 252
    *(dstGrid___0 + (23 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (3 + i)) + (((1.0 / 18.0) * 1.95) * rho) * ((1.0 + ux * (4.5 * ux + 3.0)) - u2);
#line 253
    *(dstGrid___0 + (-16 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (4 + i)) + (((1.0 / 18.0) * 1.95) * rho) * ((1.0 + ux * (4.5 * ux - 3.0)) - u2);
#line 254
    *(dstGrid___0 + (200005 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (5 + i)) + (((1.0 / 18.0) * 1.95) * rho) * ((1.0 + uz * (4.5 * uz + 3.0)) - u2);
#line 255
    *(dstGrid___0 + (-199994 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (6 + i)) + (((1.0 / 18.0) * 1.95) * rho) * ((1.0 + uz * (4.5 * uz - 3.0)) - u2);
#line 257
    *(dstGrid___0 + (2027 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (7 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (ux + uy) * (4.5 * (ux + uy) + 3.0)) - u2);
#line 258
    *(dstGrid___0 + (1988 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (8 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (- ux + uy) * (4.5 * (- ux + uy) + 3.0)) - u2);
#line 259
    *(dstGrid___0 + (-1971 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (9 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (ux - uy) * (4.5 * (ux - uy) + 3.0)) - u2);
#line 260
    *(dstGrid___0 + (-2010 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (10 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (- ux - uy) * (4.5 * (- ux - uy) + 3.0)) - u2);
#line 261
    *(dstGrid___0 + (202011 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (11 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (uy + uz) * (4.5 * (uy + uz) + 3.0)) - u2);
#line 262
    *(dstGrid___0 + (-197988 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (12 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (uy - uz) * (4.5 * (uy - uz) + 3.0)) - u2);
#line 263
    *(dstGrid___0 + (198013 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (13 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (- uy + uz) * (4.5 * (- uy + uz) + 3.0)) - u2);
#line 264
    *(dstGrid___0 + (-201986 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (14 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (- uy - uz) * (4.5 * (- uy - uz) + 3.0)) - u2);
#line 265
    *(dstGrid___0 + (200035 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (15 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (ux + uz) * (4.5 * (ux + uz) + 3.0)) - u2);
#line 266
    *(dstGrid___0 + (-199964 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (16 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (ux - uz) * (4.5 * (ux - uz) + 3.0)) - u2);
#line 267
    *(dstGrid___0 + (199997 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (17 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (- ux + uz) * (4.5 * (- ux + uz) + 3.0)) - u2);
#line 268
    *(dstGrid___0 + (-200002 + i)) = (1.0 - 1.95) * *(srcGrid___0 + (18 + i)) + (((1.0 / 36.0) * 1.95) * rho) * ((1.0 + (- ux - uz) * (4.5 * (- ux - uz) + 3.0)) - u2);
    __Cont: /* CIL Label */ 
#line 186
    i += 20;
  }
#line 270
  return;
}
}
#line 274 "lbm.c"
void LBM_handleInOutFlow(double *srcGrid___0 ) 
{ 
  double ux ;
  double uy ;
  double uz ;
  double rho ;
  double ux1 ;
  double uy1 ;
  double uz1 ;
  double rho1 ;
  double ux2 ;
  double uy2 ;
  double uz2 ;
  double rho2 ;
  double u2 ;
  double px ;
  double py ;
  int i ;

  {
#line 289
  i = 0;
#line 289
  while (i < 200000) {
#line 290
    rho1 = (((((((((((((((((*(srcGrid___0 + (200000 + i)) + *(srcGrid___0 + (200001 + i))) + *(srcGrid___0 + (200002 + i))) + *(srcGrid___0 + (200003 + i))) + *(srcGrid___0 + (200004 + i))) + *(srcGrid___0 + (200005 + i))) + *(srcGrid___0 + (200006 + i))) + *(srcGrid___0 + (200007 + i))) + *(srcGrid___0 + (200008 + i))) + *(srcGrid___0 + (200009 + i))) + *(srcGrid___0 + (200010 + i))) + *(srcGrid___0 + (200011 + i))) + *(srcGrid___0 + (200012 + i))) + *(srcGrid___0 + (200013 + i))) + *(srcGrid___0 + (200014 + i))) + *(srcGrid___0 + (200015 + i))) + *(srcGrid___0 + (200016 + i))) + *(srcGrid___0 + (200017 + i))) + *(srcGrid___0 + (200018 + i));
#line 300
    rho2 = (((((((((((((((((*(srcGrid___0 + (400000 + i)) + *(srcGrid___0 + (400001 + i))) + *(srcGrid___0 + (400002 + i))) + *(srcGrid___0 + (400003 + i))) + *(srcGrid___0 + (400004 + i))) + *(srcGrid___0 + (400005 + i))) + *(srcGrid___0 + (400006 + i))) + *(srcGrid___0 + (400007 + i))) + *(srcGrid___0 + (400008 + i))) + *(srcGrid___0 + (400009 + i))) + *(srcGrid___0 + (400010 + i))) + *(srcGrid___0 + (400011 + i))) + *(srcGrid___0 + (400012 + i))) + *(srcGrid___0 + (400013 + i))) + *(srcGrid___0 + (400014 + i))) + *(srcGrid___0 + (400015 + i))) + *(srcGrid___0 + (400016 + i))) + *(srcGrid___0 + (400017 + i))) + *(srcGrid___0 + (400018 + i));
#line 311
    rho = 2.0 * rho1 - rho2;
#line 313
    px = (double )((i / 20) % 100) / (0.5 * (double )99) - 1.0;
#line 314
    py = (double )(((i / 20) / 100) % 100) / (0.5 * (double )99) - 1.0;
#line 315
    ux = 0.00;
#line 316
    uy = 0.00;
#line 317
    uz = (0.01 * (1.0 - px * px)) * (1.0 - py * py);
#line 319
    u2 = 1.5 * ((ux * ux + uy * uy) + uz * uz);
#line 321
    *(srcGrid___0 + i) = ((1.0 / 3.0) * rho) * (1.0 - u2);
#line 323
    *(srcGrid___0 + (1 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + uy * (4.5 * uy + 3.0)) - u2);
#line 324
    *(srcGrid___0 + (2 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + uy * (4.5 * uy - 3.0)) - u2);
#line 325
    *(srcGrid___0 + (3 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + ux * (4.5 * ux + 3.0)) - u2);
#line 326
    *(srcGrid___0 + (4 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + ux * (4.5 * ux - 3.0)) - u2);
#line 327
    *(srcGrid___0 + (5 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + uz * (4.5 * uz + 3.0)) - u2);
#line 328
    *(srcGrid___0 + (6 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + uz * (4.5 * uz - 3.0)) - u2);
#line 330
    *(srcGrid___0 + (7 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (ux + uy) * (4.5 * (ux + uy) + 3.0)) - u2);
#line 331
    *(srcGrid___0 + (8 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- ux + uy) * (4.5 * (- ux + uy) + 3.0)) - u2);
#line 332
    *(srcGrid___0 + (9 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (ux - uy) * (4.5 * (ux - uy) + 3.0)) - u2);
#line 333
    *(srcGrid___0 + (10 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- ux - uy) * (4.5 * (- ux - uy) + 3.0)) - u2);
#line 334
    *(srcGrid___0 + (11 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (uy + uz) * (4.5 * (uy + uz) + 3.0)) - u2);
#line 335
    *(srcGrid___0 + (12 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (uy - uz) * (4.5 * (uy - uz) + 3.0)) - u2);
#line 336
    *(srcGrid___0 + (13 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- uy + uz) * (4.5 * (- uy + uz) + 3.0)) - u2);
#line 337
    *(srcGrid___0 + (14 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- uy - uz) * (4.5 * (- uy - uz) + 3.0)) - u2);
#line 338
    *(srcGrid___0 + (15 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (ux + uz) * (4.5 * (ux + uz) + 3.0)) - u2);
#line 339
    *(srcGrid___0 + (16 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (ux - uz) * (4.5 * (ux - uz) + 3.0)) - u2);
#line 340
    *(srcGrid___0 + (17 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- ux + uz) * (4.5 * (- ux + uz) + 3.0)) - u2);
#line 341
    *(srcGrid___0 + (18 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- ux - uz) * (4.5 * (- ux - uz) + 3.0)) - u2);
#line 289
    i += 20;
  }
#line 353
  i = 25800000;
#line 353
  while (i < 26000000) {
#line 354
    rho1 = (((((((((((((((((*(srcGrid___0 + (-200000 + i)) + *(srcGrid___0 + (-199999 + i))) + *(srcGrid___0 + (-199998 + i))) + *(srcGrid___0 + (-199997 + i))) + *(srcGrid___0 + (-199996 + i))) + *(srcGrid___0 + (-199995 + i))) + *(srcGrid___0 + (-199994 + i))) + *(srcGrid___0 + (-199993 + i))) + *(srcGrid___0 + (-199992 + i))) + *(srcGrid___0 + (-199991 + i))) + *(srcGrid___0 + (-199990 + i))) + *(srcGrid___0 + (-199989 + i))) + *(srcGrid___0 + (-199988 + i))) + *(srcGrid___0 + (-199987 + i))) + *(srcGrid___0 + (-199986 + i))) + *(srcGrid___0 + (-199985 + i))) + *(srcGrid___0 + (-199984 + i))) + *(srcGrid___0 + (-199983 + i))) + *(srcGrid___0 + (-199982 + i));
#line 364
    ux1 = ((((((((*(srcGrid___0 + (-199997 + i)) - *(srcGrid___0 + (-199996 + i))) + *(srcGrid___0 + (-199993 + i))) - *(srcGrid___0 + (-199992 + i))) + *(srcGrid___0 + (-199991 + i))) - *(srcGrid___0 + (-199990 + i))) + *(srcGrid___0 + (-199985 + i))) + *(srcGrid___0 + (-199984 + i))) - *(srcGrid___0 + (-199983 + i))) - *(srcGrid___0 + (-199982 + i));
#line 369
    uy1 = ((((((((*(srcGrid___0 + (-199999 + i)) - *(srcGrid___0 + (-199998 + i))) + *(srcGrid___0 + (-199993 + i))) + *(srcGrid___0 + (-199992 + i))) - *(srcGrid___0 + (-199991 + i))) - *(srcGrid___0 + (-199990 + i))) + *(srcGrid___0 + (-199989 + i))) + *(srcGrid___0 + (-199988 + i))) - *(srcGrid___0 + (-199987 + i))) - *(srcGrid___0 + (-199986 + i));
#line 374
    uz1 = ((((((((*(srcGrid___0 + (-199995 + i)) - *(srcGrid___0 + (-199994 + i))) + *(srcGrid___0 + (-199989 + i))) - *(srcGrid___0 + (-199988 + i))) + *(srcGrid___0 + (-199987 + i))) - *(srcGrid___0 + (-199986 + i))) + *(srcGrid___0 + (-199985 + i))) - *(srcGrid___0 + (-199984 + i))) + *(srcGrid___0 + (-199983 + i))) - *(srcGrid___0 + (-199982 + i));
#line 380
    ux1 /= rho1;
#line 381
    uy1 /= rho1;
#line 382
    uz1 /= rho1;
#line 384
    rho2 = (((((((((((((((((*(srcGrid___0 + (-400000 + i)) + *(srcGrid___0 + (-399999 + i))) + *(srcGrid___0 + (-399998 + i))) + *(srcGrid___0 + (-399997 + i))) + *(srcGrid___0 + (-399996 + i))) + *(srcGrid___0 + (-399995 + i))) + *(srcGrid___0 + (-399994 + i))) + *(srcGrid___0 + (-399993 + i))) + *(srcGrid___0 + (-399992 + i))) + *(srcGrid___0 + (-399991 + i))) + *(srcGrid___0 + (-399990 + i))) + *(srcGrid___0 + (-399989 + i))) + *(srcGrid___0 + (-399988 + i))) + *(srcGrid___0 + (-399987 + i))) + *(srcGrid___0 + (-399986 + i))) + *(srcGrid___0 + (-399985 + i))) + *(srcGrid___0 + (-399984 + i))) + *(srcGrid___0 + (-399983 + i))) + *(srcGrid___0 + (-399982 + i));
#line 394
    ux2 = ((((((((*(srcGrid___0 + (-399997 + i)) - *(srcGrid___0 + (-399996 + i))) + *(srcGrid___0 + (-399993 + i))) - *(srcGrid___0 + (-399992 + i))) + *(srcGrid___0 + (-399991 + i))) - *(srcGrid___0 + (-399990 + i))) + *(srcGrid___0 + (-399985 + i))) + *(srcGrid___0 + (-399984 + i))) - *(srcGrid___0 + (-399983 + i))) - *(srcGrid___0 + (-399982 + i));
#line 399
    uy2 = ((((((((*(srcGrid___0 + (-399999 + i)) - *(srcGrid___0 + (-399998 + i))) + *(srcGrid___0 + (-399993 + i))) + *(srcGrid___0 + (-399992 + i))) - *(srcGrid___0 + (-399991 + i))) - *(srcGrid___0 + (-399990 + i))) + *(srcGrid___0 + (-399989 + i))) + *(srcGrid___0 + (-399988 + i))) - *(srcGrid___0 + (-399987 + i))) - *(srcGrid___0 + (-399986 + i));
#line 404
    uz2 = ((((((((*(srcGrid___0 + (-399995 + i)) - *(srcGrid___0 + (-399994 + i))) + *(srcGrid___0 + (-399989 + i))) - *(srcGrid___0 + (-399988 + i))) + *(srcGrid___0 + (-399987 + i))) - *(srcGrid___0 + (-399986 + i))) + *(srcGrid___0 + (-399985 + i))) - *(srcGrid___0 + (-399984 + i))) + *(srcGrid___0 + (-399983 + i))) - *(srcGrid___0 + (-399982 + i));
#line 410
    ux2 /= rho2;
#line 411
    uy2 /= rho2;
#line 412
    uz2 /= rho2;
#line 414
    rho = 1.0;
#line 416
    ux = (double )2 * ux1 - ux2;
#line 417
    uy = (double )2 * uy1 - uy2;
#line 418
    uz = (double )2 * uz1 - uz2;
#line 420
    u2 = 1.5 * ((ux * ux + uy * uy) + uz * uz);
#line 422
    *(srcGrid___0 + i) = ((1.0 / 3.0) * rho) * (1.0 - u2);
#line 424
    *(srcGrid___0 + (1 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + uy * (4.5 * uy + 3.0)) - u2);
#line 425
    *(srcGrid___0 + (2 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + uy * (4.5 * uy - 3.0)) - u2);
#line 426
    *(srcGrid___0 + (3 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + ux * (4.5 * ux + 3.0)) - u2);
#line 427
    *(srcGrid___0 + (4 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + ux * (4.5 * ux - 3.0)) - u2);
#line 428
    *(srcGrid___0 + (5 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + uz * (4.5 * uz + 3.0)) - u2);
#line 429
    *(srcGrid___0 + (6 + i)) = ((1.0 / 18.0) * rho) * ((1.0 + uz * (4.5 * uz - 3.0)) - u2);
#line 431
    *(srcGrid___0 + (7 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (ux + uy) * (4.5 * (ux + uy) + 3.0)) - u2);
#line 432
    *(srcGrid___0 + (8 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- ux + uy) * (4.5 * (- ux + uy) + 3.0)) - u2);
#line 433
    *(srcGrid___0 + (9 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (ux - uy) * (4.5 * (ux - uy) + 3.0)) - u2);
#line 434
    *(srcGrid___0 + (10 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- ux - uy) * (4.5 * (- ux - uy) + 3.0)) - u2);
#line 435
    *(srcGrid___0 + (11 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (uy + uz) * (4.5 * (uy + uz) + 3.0)) - u2);
#line 436
    *(srcGrid___0 + (12 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (uy - uz) * (4.5 * (uy - uz) + 3.0)) - u2);
#line 437
    *(srcGrid___0 + (13 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- uy + uz) * (4.5 * (- uy + uz) + 3.0)) - u2);
#line 438
    *(srcGrid___0 + (14 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- uy - uz) * (4.5 * (- uy - uz) + 3.0)) - u2);
#line 439
    *(srcGrid___0 + (15 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (ux + uz) * (4.5 * (ux + uz) + 3.0)) - u2);
#line 440
    *(srcGrid___0 + (16 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (ux - uz) * (4.5 * (ux - uz) + 3.0)) - u2);
#line 441
    *(srcGrid___0 + (17 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- ux + uz) * (4.5 * (- ux + uz) + 3.0)) - u2);
#line 442
    *(srcGrid___0 + (18 + i)) = ((1.0 / 36.0) * rho) * ((1.0 + (- ux - uz) * (4.5 * (- ux - uz) + 3.0)) - u2);
#line 353
    i += 20;
  }
#line 444
  return;
}
}
#line 448 "lbm.c"
void LBM_showGridStatistics(double *grid ) 
{ 
  int nObstacleCells ;
  int nAccelCells ;
  int nFluidCells ;
  double ux ;
  double uy ;
  double uz ;
  double minU2 ;
  double maxU2 ;
  double u2 ;
  double minRho ;
  double maxRho ;
  double rho ;
  double mass ;
  int i ;
  double tmp ;
  double tmp___0 ;

  {
#line 449
  nObstacleCells = 0;
#line 449
  nAccelCells = 0;
#line 449
  nFluidCells = 0;
#line 453
  minU2 = 1e+30;
#line 453
  maxU2 = - 1e+30;
#line 454
  minRho = 1e+30;
#line 454
  maxRho = - 1e+30;
#line 455
  mass = (double )0;
#line 459
  i = 0;
#line 459
  while (i < 26000000) {
#line 460
    rho = (((((((((((((((((*(grid + i) + *(grid + (1 + i))) + *(grid + (2 + i))) + *(grid + (3 + i))) + *(grid + (4 + i))) + *(grid + (5 + i))) + *(grid + (6 + i))) + *(grid + (7 + i))) + *(grid + (8 + i))) + *(grid + (9 + i))) + *(grid + (10 + i))) + *(grid + (11 + i))) + *(grid + (12 + i))) + *(grid + (13 + i))) + *(grid + (14 + i))) + *(grid + (15 + i))) + *(grid + (16 + i))) + *(grid + (17 + i))) + *(grid + (18 + i));
#line 470
    if (rho < minRho) {
#line 470
      minRho = rho;
    }
#line 471
    if (rho > maxRho) {
#line 471
      maxRho = rho;
    }
#line 472
    mass += rho;
#line 474
    if (*((unsigned int *)((void *)(grid + (19 + i)))) & 1U) {
#line 475
      nObstacleCells ++;
    } else {
#line 478
      if (*((unsigned int *)((void *)(grid + (19 + i)))) & 2U) {
#line 479
        nAccelCells ++;
      } else {
#line 481
        nFluidCells ++;
      }
#line 483
      ux = ((((((((*(grid + (3 + i)) - *(grid + (4 + i))) + *(grid + (7 + i))) - *(grid + (8 + i))) + *(grid + (9 + i))) - *(grid + (10 + i))) + *(grid + (15 + i))) + *(grid + (16 + i))) - *(grid + (17 + i))) - *(grid + (18 + i));
#line 488
      uy = ((((((((*(grid + (1 + i)) - *(grid + (2 + i))) + *(grid + (7 + i))) + *(grid + (8 + i))) - *(grid + (9 + i))) - *(grid + (10 + i))) + *(grid + (11 + i))) + *(grid + (12 + i))) - *(grid + (13 + i))) - *(grid + (14 + i));
#line 493
      uz = ((((((((*(grid + (5 + i)) - *(grid + (6 + i))) + *(grid + (11 + i))) - *(grid + (12 + i))) + *(grid + (13 + i))) - *(grid + (14 + i))) + *(grid + (15 + i))) - *(grid + (16 + i))) + *(grid + (17 + i))) - *(grid + (18 + i));
#line 498
      u2 = ((ux * ux + uy * uy) + uz * uz) / (rho * rho);
#line 499
      if (u2 < minU2) {
#line 499
        minU2 = u2;
      }
#line 500
      if (u2 > maxU2) {
#line 500
        maxU2 = u2;
      }
    }
#line 459
    i += 20;
  }
#line 504
  tmp = sqrt(maxU2);
#line 504
  tmp___0 = sqrt(minU2);
#line 504
  printf((char const   * __restrict  )"LBM_showGridStatistics:\n\tnObstacleCells: %7i nAccelCells: %7i nFluidCells: %7i\n\tminRho: %8.4f maxRho: %8.4f mass: %e\n\tminU: %e maxU: %e\n\n",
         nObstacleCells, nAccelCells, nFluidCells, minRho, maxRho, mass, tmp___0,
         tmp);
#line 512
  return;
}
}
#line 516 "lbm.c"
static void storeValue(FILE *file , float *v ) 
{ 
  int litteBigEndianTest ;
  char const   *vPtr ;
  char buffer[sizeof(float )] ;
  int i ;

  {
#line 517
  litteBigEndianTest = 1;
#line 518
  if ((int )*((unsigned char *)(& litteBigEndianTest)) == 0) {
#line 519
    vPtr = (char const   *)((char *)v);
#line 523
    i = 0;
#line 523
    while ((unsigned long )i < sizeof(float )) {
#line 524
      buffer[i] = (char )*(vPtr + ((sizeof(float ) - (unsigned long )i) - 1UL));
#line 523
      i ++;
    }
#line 526
    fwrite((void const   * __restrict  )(buffer), sizeof(float ), (size_t )1, (FILE * __restrict  )file);
  } else {
#line 529
    fwrite((void const   * __restrict  )v, sizeof(float ), (size_t )1, (FILE * __restrict  )file);
  }
#line 531
  return;
}
}
#line 535 "lbm.c"
static void loadValue(FILE *file , float *v ) 
{ 
  int litteBigEndianTest ;
  char *vPtr ;
  char buffer[sizeof(float )] ;
  int i ;

  {
#line 536
  litteBigEndianTest = 1;
#line 537
  if ((int )*((unsigned char *)(& litteBigEndianTest)) == 0) {
#line 538
    vPtr = (char *)v;
#line 542
    fread((void * __restrict  )(buffer), sizeof(float ), (size_t )1, (FILE * __restrict  )file);
#line 544
    i = 0;
#line 544
    while ((unsigned long )i < sizeof(float )) {
#line 545
      *(vPtr + i) = buffer[(sizeof(float ) - (unsigned long )i) - 1UL];
#line 544
      i ++;
    }
  } else {
#line 548
    fread((void * __restrict  )v, sizeof(float ), (size_t )1, (FILE * __restrict  )file);
  }
#line 550
  return;
}
}
#line 554 "lbm.c"
void LBM_storeVelocityField(double *grid , char const   *filename , int const   binary ) 
{ 
  int x ;
  int y ;
  int z ;
  float rho ;
  float ux ;
  float uy ;
  float uz ;
  FILE *file ;
  char const   *tmp ;
  FILE *tmp___0 ;

  {
#line 559
  if (binary) {
#line 559
    tmp = "wb";
  } else {
#line 559
    tmp = "w";
  }
#line 559
  tmp___0 = fopen((char const   * __restrict  )filename, (char const   * __restrict  )tmp);
#line 559
  file = tmp___0;
#line 561
  z = 0;
#line 561
  while (z < 130) {
#line 562
    y = 0;
#line 562
    while (y < 100) {
#line 563
      x = 0;
#line 563
      while (x < 100) {
#line 564
        rho = (float )((((((((((((((((((*(grid + 20 * ((x + y * 100) + (z * 100) * 100)) + *(grid + (1 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (2 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (3 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (4 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (5 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (6 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (7 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (8 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (9 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (10 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (11 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (12 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (13 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (14 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (15 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (16 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (17 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (18 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 574
        ux = (float )(((((((((*(grid + (3 + 20 * ((x + y * 100) + (z * 100) * 100))) - *(grid + (4 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (7 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (8 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (9 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (10 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (15 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (16 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (17 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (18 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 579
        uy = (float )(((((((((*(grid + (1 + 20 * ((x + y * 100) + (z * 100) * 100))) - *(grid + (2 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (7 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (8 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (9 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (10 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (11 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (12 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (13 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (14 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 584
        uz = (float )(((((((((*(grid + (5 + 20 * ((x + y * 100) + (z * 100) * 100))) - *(grid + (6 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (11 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (12 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (13 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (14 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (15 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (16 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (17 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (18 + 20 * ((x + y * 100) + (z * 100) * 100))));
#line 589
        ux /= rho;
#line 590
        uy /= rho;
#line 591
        uz /= rho;
#line 593
        if (binary) {
#line 599
          storeValue(file, & ux);
#line 600
          storeValue(file, & uy);
#line 601
          storeValue(file, & uz);
        } else {
#line 603
          fprintf((FILE * __restrict  )file, (char const   * __restrict  )"%e %e %e\n",
                  (double )ux, (double )uy, (double )uz);
        }
#line 563
        x ++;
      }
#line 562
      y ++;
    }
#line 561
    z ++;
  }
#line 609
  fclose(file);
#line 610
  return;
}
}
#line 614 "lbm.c"
void LBM_compareVelocityField(double *grid , char const   *filename , int const   binary ) 
{ 
  int x ;
  int y ;
  int z ;
  double rho ;
  double ux ;
  double uy ;
  double uz ;
  float fileUx ;
  float fileUy ;
  float fileUz ;
  float dUx ;
  float dUy ;
  float dUz ;
  float diff2 ;
  float maxDiff2 ;
  FILE *file ;
  char const   *tmp ;
  FILE *tmp___0 ;
  double tmp___1 ;

  {
#line 618
  maxDiff2 = (float )(- 1e+30);
#line 622
  if (binary) {
#line 622
    tmp = "rb";
  } else {
#line 622
    tmp = "r";
  }
#line 622
  tmp___0 = fopen((char const   * __restrict  )filename, (char const   * __restrict  )tmp);
#line 622
  file = tmp___0;
#line 624
  z = 0;
#line 624
  while (z < 130) {
#line 625
    y = 0;
#line 625
    while (y < 100) {
#line 626
      x = 0;
#line 626
      while (x < 100) {
#line 627
        rho = (((((((((((((((((*(grid + 20 * ((x + y * 100) + (z * 100) * 100)) + *(grid + (1 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (2 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (3 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (4 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (5 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (6 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (7 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (8 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (9 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (10 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (11 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (12 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (13 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (14 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (15 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (16 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (17 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (18 + 20 * ((x + y * 100) + (z * 100) * 100)));
#line 637
        ux = ((((((((*(grid + (3 + 20 * ((x + y * 100) + (z * 100) * 100))) - *(grid + (4 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (7 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (8 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (9 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (10 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (15 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (16 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (17 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (18 + 20 * ((x + y * 100) + (z * 100) * 100)));
#line 642
        uy = ((((((((*(grid + (1 + 20 * ((x + y * 100) + (z * 100) * 100))) - *(grid + (2 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (7 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (8 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (9 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (10 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (11 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (12 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (13 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (14 + 20 * ((x + y * 100) + (z * 100) * 100)));
#line 647
        uz = ((((((((*(grid + (5 + 20 * ((x + y * 100) + (z * 100) * 100))) - *(grid + (6 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (11 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (12 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (13 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (14 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (15 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (16 + 20 * ((x + y * 100) + (z * 100) * 100)))) + *(grid + (17 + 20 * ((x + y * 100) + (z * 100) * 100)))) - *(grid + (18 + 20 * ((x + y * 100) + (z * 100) * 100)));
#line 652
        ux /= rho;
#line 653
        uy /= rho;
#line 654
        uz /= rho;
#line 656
        if (binary) {
#line 657
          loadValue(file, & fileUx);
#line 658
          loadValue(file, & fileUy);
#line 659
          loadValue(file, & fileUz);
        } else
#line 662
        if (sizeof(float ) == sizeof(double )) {
#line 663
          fscanf((FILE * __restrict  )file, (char const   * __restrict  )"%lf %lf %lf\n",
                 & fileUx, & fileUy, & fileUz);
        } else {
#line 666
          fscanf((FILE * __restrict  )file, (char const   * __restrict  )"%f %f %f\n",
                 & fileUx, & fileUy, & fileUz);
        }
#line 670
        dUx = (float )(ux - (double )fileUx);
#line 671
        dUy = (float )(uy - (double )fileUy);
#line 672
        dUz = (float )(uz - (double )fileUz);
#line 673
        diff2 = (dUx * dUx + dUy * dUy) + dUz * dUz;
#line 674
        if (diff2 > maxDiff2) {
#line 674
          maxDiff2 = diff2;
        }
#line 626
        x ++;
      }
#line 625
      y ++;
    }
#line 624
    z ++;
  }
#line 680
  tmp___1 = sqrt((double )maxDiff2);
#line 680
  printf((char const   * __restrict  )"LBM_compareVelocityField: maxDiff = %e  \n\n",
         tmp___1);
#line 687
  fclose(file);
#line 688
  return;
}
}
#line 1 "main.o"
#pragma merger("0","/tmp/cil-aSWx9PM7.i","")
#line 40 "./main.h"
void MAIN_parseCommandLine(int nArgs , char **arg , MAIN_Param *param ) ;
#line 41
void MAIN_printInfo(MAIN_Param const   *param ) ;
#line 42
void MAIN_initialize(MAIN_Param const   *param ) ;
#line 43
void MAIN_finalize(MAIN_Param const   *param ) ;
#line 104 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1))) atoi)(char const   *__nptr )  __attribute__((__pure__)) ;
#line 205 "/usr/include/x86_64-linux-gnu/sys/stat.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2))) stat)(char const   * __restrict  __file ,
                                                                                   struct stat * __restrict  __buf ) ;
#line 21 "main.c"
static LBM_GridPtr srcGrid  ;
#line 21 "main.c"
static LBM_GridPtr dstGrid  ;
#line 25 "main.c"
int main(int nArgs , char **arg ) 
{ 
  MAIN_Param param ;
  int t ;

  {
#line 32
  MAIN_parseCommandLine(nArgs, arg, & param);
#line 33
  MAIN_printInfo((MAIN_Param const   *)(& param));
#line 34
  MAIN_initialize((MAIN_Param const   *)(& param));
#line 39
  t = 1;
#line 39
  while (t <= param.nTimeSteps) {
#line 40
    if ((unsigned int )param.simType == 1U) {
#line 41
      LBM_handleInOutFlow((double *)(*srcGrid));
    }
#line 44
    LBM_performStreamCollide((double *)(*srcGrid), (double *)(*dstGrid));
#line 45
    LBM_swapGrids(& srcGrid, & dstGrid);
#line 47
    if ((t & 63) == 0) {
#line 48
      printf((char const   * __restrict  )"timestep: %i\n", t);
#line 49
      LBM_showGridStatistics((double *)(*srcGrid));
    }
#line 39
    t ++;
  }
#line 56
  MAIN_finalize((MAIN_Param const   *)(& param));
#line 58
  return (0);
}
}
#line 63 "main.c"
void MAIN_parseCommandLine(int nArgs , char **arg , MAIN_Param *param ) 
{ 
  struct stat fileStat ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;

  {
#line 66
  if (nArgs < 5) {
#line 67
    printf((char const   * __restrict  )"syntax: lbm <time steps> <result file> <0: nil, 1: cmp, 2: str> <0: ldc, 1: channel flow> [<obstacle file>]\n");
#line 68
    exit(1);
  } else
#line 66
  if (nArgs > 6) {
#line 67
    printf((char const   * __restrict  )"syntax: lbm <time steps> <result file> <0: nil, 1: cmp, 2: str> <0: ldc, 1: channel flow> [<obstacle file>]\n");
#line 68
    exit(1);
  }
#line 71
  param->nTimeSteps = atoi((char const   *)*(arg + 1));
#line 72
  param->resultFilename = *(arg + 2);
#line 73
  tmp = atoi((char const   *)*(arg + 3));
#line 73
  param->action = (MAIN_Action )tmp;
#line 74
  tmp___0 = atoi((char const   *)*(arg + 4));
#line 74
  param->simType = (MAIN_SimType )tmp___0;
#line 76
  if (nArgs == 6) {
#line 77
    param->obstacleFilename = *(arg + 5);
#line 79
    tmp___1 = stat((char const   * __restrict  )param->obstacleFilename, (struct stat * __restrict  )(& fileStat));
#line 79
    if (tmp___1 != 0) {
#line 80
      printf((char const   * __restrict  )"MAIN_parseCommandLine: cannot stat obstacle file \'%s\'\n",
             param->obstacleFilename);
#line 82
      exit(1);
    }
#line 84
    if (fileStat.st_size != 1313130L) {
#line 85
      printf((char const   * __restrict  )"MAIN_parseCommandLine:\n\tsize of file \'%s\' is %i bytes\n\texpected size is %i bytes\n",
             param->obstacleFilename, (int )fileStat.st_size, 1313130);
#line 90
      exit(1);
    }
  } else {
#line 93
    param->obstacleFilename = (char *)((void *)0);
  }
#line 95
  if ((unsigned int )param->action == 1U) {
#line 95
    tmp___2 = stat((char const   * __restrict  )param->resultFilename, (struct stat * __restrict  )(& fileStat));
#line 95
    if (tmp___2 != 0) {
#line 97
      printf((char const   * __restrict  )"MAIN_parseCommandLine: cannot stat result file \'%s\'\n",
             param->resultFilename);
#line 99
      exit(1);
    }
  }
#line 101
  return;
}
}
#line 105 "main.c"
void MAIN_printInfo(MAIN_Param const   *param ) 
{ 
  char actionString[3][32] ;
  unsigned int tmp ;
  unsigned int tmp___0 ;
  unsigned int tmp___1 ;
  char simTypeString[3][32] ;
  unsigned int tmp___2 ;
  unsigned int tmp___3 ;
  unsigned int tmp___4 ;
  char const   *tmp___5 ;

  {
#line 106
  actionString[0][0] = (char )'n';
#line 106
  actionString[0][1] = (char )'o';
#line 106
  actionString[0][2] = (char )'t';
#line 106
  actionString[0][3] = (char )'h';
#line 106
  actionString[0][4] = (char )'i';
#line 106
  actionString[0][5] = (char )'n';
#line 106
  actionString[0][6] = (char )'g';
#line 106
  actionString[0][7] = (char )'\000';
#line 106
  tmp = 8U;
#line 106
  while (! (tmp >= 32U)) {
#line 106
    actionString[0][tmp] = (char)0;
#line 106
    tmp ++;
  }
#line 106
  actionString[1][0] = (char )'c';
#line 106
  actionString[1][1] = (char )'o';
#line 106
  actionString[1][2] = (char )'m';
#line 106
  actionString[1][3] = (char )'p';
#line 106
  actionString[1][4] = (char )'a';
#line 106
  actionString[1][5] = (char )'r';
#line 106
  actionString[1][6] = (char )'e';
#line 106
  actionString[1][7] = (char )'\000';
#line 106
  tmp___0 = 8U;
#line 106
  while (! (tmp___0 >= 32U)) {
#line 106
    actionString[1][tmp___0] = (char)0;
#line 106
    tmp___0 ++;
  }
#line 106
  actionString[2][0] = (char )'s';
#line 106
  actionString[2][1] = (char )'t';
#line 106
  actionString[2][2] = (char )'o';
#line 106
  actionString[2][3] = (char )'r';
#line 106
  actionString[2][4] = (char )'e';
#line 106
  actionString[2][5] = (char )'\000';
#line 106
  tmp___1 = 6U;
#line 106
  while (! (tmp___1 >= 32U)) {
#line 106
    actionString[2][tmp___1] = (char)0;
#line 106
    tmp___1 ++;
  }
#line 107
  simTypeString[0][0] = (char )'l';
#line 107
  simTypeString[0][1] = (char )'i';
#line 107
  simTypeString[0][2] = (char )'d';
#line 107
  simTypeString[0][3] = (char )'-';
#line 107
  simTypeString[0][4] = (char )'d';
#line 107
  simTypeString[0][5] = (char )'r';
#line 107
  simTypeString[0][6] = (char )'i';
#line 107
  simTypeString[0][7] = (char )'v';
#line 107
  simTypeString[0][8] = (char )'e';
#line 107
  simTypeString[0][9] = (char )'n';
#line 107
  simTypeString[0][10] = (char )' ';
#line 107
  simTypeString[0][11] = (char )'c';
#line 107
  simTypeString[0][12] = (char )'a';
#line 107
  simTypeString[0][13] = (char )'v';
#line 107
  simTypeString[0][14] = (char )'i';
#line 107
  simTypeString[0][15] = (char )'t';
#line 107
  simTypeString[0][16] = (char )'y';
#line 107
  simTypeString[0][17] = (char )'\000';
#line 107
  tmp___2 = 18U;
#line 107
  while (! (tmp___2 >= 32U)) {
#line 107
    simTypeString[0][tmp___2] = (char)0;
#line 107
    tmp___2 ++;
  }
#line 107
  simTypeString[1][0] = (char )'c';
#line 107
  simTypeString[1][1] = (char )'h';
#line 107
  simTypeString[1][2] = (char )'a';
#line 107
  simTypeString[1][3] = (char )'n';
#line 107
  simTypeString[1][4] = (char )'n';
#line 107
  simTypeString[1][5] = (char )'e';
#line 107
  simTypeString[1][6] = (char )'l';
#line 107
  simTypeString[1][7] = (char )' ';
#line 107
  simTypeString[1][8] = (char )'f';
#line 107
  simTypeString[1][9] = (char )'l';
#line 107
  simTypeString[1][10] = (char )'o';
#line 107
  simTypeString[1][11] = (char )'w';
#line 107
  simTypeString[1][12] = (char )'\000';
#line 107
  tmp___3 = 13U;
#line 107
  while (! (tmp___3 >= 32U)) {
#line 107
    simTypeString[1][tmp___3] = (char)0;
#line 107
    tmp___3 ++;
  }
#line 107
  tmp___4 = 2U;
#line 107
  while (! (tmp___4 >= 3U)) {
#line 107
    simTypeString[tmp___4][0] = (char)0;
#line 107
    simTypeString[tmp___4][1] = (char)0;
#line 107
    simTypeString[tmp___4][2] = (char)0;
#line 107
    simTypeString[tmp___4][3] = (char)0;
#line 107
    simTypeString[tmp___4][4] = (char)0;
#line 107
    simTypeString[tmp___4][5] = (char)0;
#line 107
    simTypeString[tmp___4][6] = (char)0;
#line 107
    simTypeString[tmp___4][7] = (char)0;
#line 107
    simTypeString[tmp___4][8] = (char)0;
#line 107
    simTypeString[tmp___4][9] = (char)0;
#line 107
    simTypeString[tmp___4][10] = (char)0;
#line 107
    simTypeString[tmp___4][11] = (char)0;
#line 107
    simTypeString[tmp___4][12] = (char)0;
#line 107
    simTypeString[tmp___4][13] = (char)0;
#line 107
    simTypeString[tmp___4][14] = (char)0;
#line 107
    simTypeString[tmp___4][15] = (char)0;
#line 107
    simTypeString[tmp___4][16] = (char)0;
#line 107
    simTypeString[tmp___4][17] = (char)0;
#line 107
    simTypeString[tmp___4][18] = (char)0;
#line 107
    simTypeString[tmp___4][19] = (char)0;
#line 107
    simTypeString[tmp___4][20] = (char)0;
#line 107
    simTypeString[tmp___4][21] = (char)0;
#line 107
    simTypeString[tmp___4][22] = (char)0;
#line 107
    simTypeString[tmp___4][23] = (char)0;
#line 107
    simTypeString[tmp___4][24] = (char)0;
#line 107
    simTypeString[tmp___4][25] = (char)0;
#line 107
    simTypeString[tmp___4][26] = (char)0;
#line 107
    simTypeString[tmp___4][27] = (char)0;
#line 107
    simTypeString[tmp___4][28] = (char)0;
#line 107
    simTypeString[tmp___4][29] = (char)0;
#line 107
    simTypeString[tmp___4][30] = (char)0;
#line 107
    simTypeString[tmp___4][31] = (char)0;
#line 107
    tmp___4 ++;
  }
#line 108
  if ((unsigned long )param->obstacleFilename == (unsigned long )((void *)0)) {
#line 108
    tmp___5 = (char const   * const  )"<none>";
  } else {
#line 108
    tmp___5 = (char const   * const  )param->obstacleFilename;
  }
#line 108
  printf((char const   * __restrict  )"MAIN_printInfo:\n\tgrid size      : %i x %i x %i = %.2f * 10^6 Cells\n\tnTimeSteps     : %i\n\tresult file    : %s\n\taction         : %s\n\tsimulation type: %s\n\tobstacle file  : %s\n\n",
         100, 100, 130, ((1e-6 * (double )100) * (double )100) * (double )130, param->nTimeSteps,
         param->resultFilename, actionString[param->action], simTypeString[param->simType],
         tmp___5);
#line 120
  return;
}
}
#line 124 "main.c"
void MAIN_initialize(MAIN_Param const   *param ) 
{ 


  {
#line 125
  LBM_allocateGrid((double **)(& srcGrid));
#line 126
  LBM_allocateGrid((double **)(& dstGrid));
#line 128
  LBM_initializeGrid((double *)(*srcGrid));
#line 129
  LBM_initializeGrid((double *)(*dstGrid));
#line 131
  if ((unsigned long )param->obstacleFilename != (unsigned long )((void *)0)) {
#line 132
    LBM_loadObstacleFile((double *)(*srcGrid), (char const   *)param->obstacleFilename);
#line 133
    LBM_loadObstacleFile((double *)(*dstGrid), (char const   *)param->obstacleFilename);
  }
#line 136
  if ((unsigned int const   )param->simType == 1U) {
#line 137
    LBM_initializeSpecialCellsForChannel((double *)(*srcGrid));
#line 138
    LBM_initializeSpecialCellsForChannel((double *)(*dstGrid));
  } else {
#line 141
    LBM_initializeSpecialCellsForLDC((double *)(*srcGrid));
#line 142
    LBM_initializeSpecialCellsForLDC((double *)(*dstGrid));
  }
#line 145
  LBM_showGridStatistics((double *)(*srcGrid));
#line 146
  return;
}
}
#line 150 "main.c"
void MAIN_finalize(MAIN_Param const   *param ) 
{ 


  {
#line 151
  LBM_showGridStatistics((double *)(*srcGrid));
#line 153
  if ((unsigned int const   )param->action == 1U) {
#line 154
    LBM_compareVelocityField((double *)(*srcGrid), (char const   *)param->resultFilename,
                             (int const   )-1);
  }
#line 155
  if ((unsigned int const   )param->action == 2U) {
#line 156
    LBM_storeVelocityField((double *)(*srcGrid), (char const   *)param->resultFilename,
                           (int const   )-1);
  }
#line 158
  LBM_freeGrid((double **)(& srcGrid));
#line 159
  LBM_freeGrid((double **)(& dstGrid));
#line 160
  return;
}
}
