// Code generated by "stringer -type=ValueTypeKind"; DO NOT EDIT.

package spir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TY_CHAR-0]
	_ = x[TY_INT8-1]
	_ = x[TY_INT16-2]
	_ = x[TY_INT32-3]
	_ = x[TY_INT64-4]
	_ = x[TY_UINT8-5]
	_ = x[TY_UCHAR-5]
	_ = x[TY_UINT16-6]
	_ = x[TY_UINT32-7]
	_ = x[TY_UINT64-8]
	_ = x[TY_N_BITS-9]
	_ = x[TY_N_UBITS-10]
	_ = x[TY_BOOL-11]
	_ = x[TY_FLOAT16-12]
	_ = x[TY_FLOAT32-13]
	_ = x[TY_FLOAT-13]
	_ = x[TY_FLOAT64-14]
	_ = x[TY_DOUBLE-14]
	_ = x[TY_PTR_TO_VOID-15]
	_ = x[TY_PTR_TO_PTR-16]
	_ = x[TY_PTR_TO_ARR-17]
	_ = x[TY_PTR_TO_CHAR-18]
	_ = x[TY_PTR_TO_INT-19]
	_ = x[TY_PTR_TO_FLOAT-20]
	_ = x[TY_PTR_TO_RECORD-21]
	_ = x[TY_PTR_TO_FUNC-22]
	_ = x[TY_ARR-23]
	_ = x[TY_UNION-24]
	_ = x[TY_STRUCT-25]
	_ = x[TY_OTHER-31]
}

const (
	_ValueTypeKind_name_0 = "TY_CHARTY_INT8TY_INT16TY_INT32TY_INT64TY_UINT8TY_UINT16TY_UINT32TY_UINT64TY_N_BITSTY_N_UBITSTY_BOOLTY_FLOAT16TY_FLOAT32TY_FLOAT64TY_PTR_TO_VOIDTY_PTR_TO_PTRTY_PTR_TO_ARRTY_PTR_TO_CHARTY_PTR_TO_INTTY_PTR_TO_FLOATTY_PTR_TO_RECORDTY_PTR_TO_FUNCTY_ARRTY_UNIONTY_STRUCT"
	_ValueTypeKind_name_1 = "TY_OTHER"
)

var (
	_ValueTypeKind_index_0 = [...]uint16{0, 7, 14, 22, 30, 38, 46, 55, 64, 73, 82, 92, 99, 109, 119, 129, 143, 156, 169, 183, 196, 211, 227, 241, 247, 255, 264}
)

func (i ValueTypeKind) String() string {
	switch {
	case i <= 25:
		return _ValueTypeKind_name_0[_ValueTypeKind_index_0[i]:_ValueTypeKind_index_0[i+1]]
	case i == 31:
		return _ValueTypeKind_name_1
	default:
		return "ValueTypeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
