/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#pragma merger("0","/tmp/cil-DkqUyAn1.i","")
int var ;
int foo(void) ;
int main(void) 
{ 
  int tmp ;

  {
  tmp = foo();
  return (var / tmp);
}
}
#pragma merger("0","/tmp/cil-_WuGFXrN.i","")
int var  =    10;
int foo(void) 
{ 


  {
  return (0);
}
}
