// Code generated by "stringer -type=FactChanged"; DO NOT EDIT.

package lattice

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoChange-0]
	_ = x[Changed-1]
	_ = x[OnlyInChanged-2]
	_ = x[OnlyOutChanged-3]
	_ = x[OnlyTrueOutChanged-5]
	_ = x[OnlyFalseOutChanged-6]
	_ = x[InOutChanged-4]
}

const _FactChanged_name = "NoChangeChangedOnlyInChangedOnlyOutChangedInOutChangedOnlyTrueOutChangedOnlyFalseOutChanged"

var _FactChanged_index = [...]uint8{0, 8, 15, 28, 42, 54, 72, 91}

func (i FactChanged) String() string {
	if i >= FactChanged(len(_FactChanged_index)-1) {
		return "FactChanged(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FactChanged_name[_FactChanged_index[i]:_FactChanged_index[i+1]]
}
